apiVersion: v1
kind: Namespace
metadata:
  name: kcrowtest
  annotations:
    nofile.rlimit.kcrow.io: '{"hard":65535,"soft":65535}'
    cpu.cgroup.kcrow.io: '{"cpus":"0-2"}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: kcrowtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-1
      containers:
      - name: helloworld
        image: nginx:1.21
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent