{{- if not .Values.controller.kubeconfig }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcrow-controller-admin
rules:
- apiGroups:
  - ""
  resources:
  - ""
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}