{{- if .Values.controller.serviceAccount.create }}
{{- if not .Values.controller.kubeconfig }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
